### ISSUE TITLE
Request for permission for inclusion in user showcase of xd-dialog-helper

### ISSUE THREAD

**Issue by pklaschka** [satriaajiputra/tunda-image#6]
Hi.

As I can see, you're using xd-dialog-helper for the plugin (by the way: thank you very much for linking to the library in your README :+1: ). With your permission, I would like to include your plugin in the user showcase of the xd-dialog-helper homepage (https://xd-dialog-helper.pabloklaschka.de/users.html).

With your permission, I would therefore like to use

- the [plugin logo](https://github.com/satriaajiputra/tunda-image/blob/master/src/tunda_image%405x.png)
- the plugin name (Tunda Image)
- a link to the plugin (the repo url or any other link specified by you)
- your summary text (*Fill any image to your shape*)

on the page linked to above.

BTW: I've just released v1.0.0 of the library, which (with almost no changes in your code required) adds improved support for UXP 3 and more...

Thank you very much in advance,
Happy coding :slightly_smiling_face: ,
Pablo

**Comment by satriaajiputra** [comment]
Hello @pklaschka, thanks for creating awesome helper like [xd-dialog-helper](https://xd-dialog-helper.pabloklaschka.de/). You can include it to your plugin user showcase. I appreciate it

**Comment by pklaschka** [comment]
Perfect, thank you very much. You're plugin is now included in the user showcase (https://xd-dialog-helper.pabloklaschka.de/users.html) and I've included the license notice in https://github.com/pklaschka/xd-dialog-helper-docs/blob/master/website/static/img/users/LICENSE.

Again, thank you very much and have a great day :slightly_smiling_face:
